name: coodig_mobile
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_riverpod: ^2.1.1
  equatable: ^2.0.3
  http: ^0.13.5
  flutter_secure_storage: ^8.0.0
  modal_progress_hud_nsn: ^0.3.0
  uni_links: ^0.5.0
  url_launcher: ^6.1.10
  flutter_dotenv: ^5.0.2
  crypto: ^3.0.2
  flutter_flavor: ^3.1.1
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  mockito: ^5.4.0
  envied: ^0.3.0+3
  shared_preferences: ^2.2.0
  flutter_launcher_icons: ^0.13.1
  local_auth: ^2.1.6
  json_annotation: ^4.8.1
  firebase_core: ^2.15.0
  firebase_analytics: ^10.4.4
  package_info_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  freezed:
  envied_generator:
  json_serializable:

flutter:
  uses-material-design: true

  assets:
    - images/
    - .env

flutter_icons:
  android: true
  ios: true
  image_path_android: 'images/android_icon.png'
  image_path_ios: 'images/app_icon.png'
  adaptive_icon_background: "#ff0000"
