name: Flutter Analyze

on: push

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create .env file
        run: cp -pr .env.example .env

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          flutter-version: 3.7.12

      - name: Run flutter pub get
        run: flutter pub get

      - name: Build runner
        run: flutter pub pub run build_runner build --delete-conflicting-outputs

      - name: Run flutter analyze
        run: flutter analyze
